baseURL = "https://amercader.net/"
languageCode = "en-gb"
title = "Adrià Mercader"
theme = "pulp"

[params]
    author = "Adrià Mercader"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    publicationYear = "2019"
    custom_css = ["/css/custom.css"]


[[menu.main]]
    identifier = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:amercadero@gmail.com"
    weight = 20

[[menu.main]]
    identifier = "Mastodon"
    pre = "<i class='fab fa-mastodon fa-lg'></i>"
    url = "https://mastodon.social/@amercader"
    weight = 25

[[menu.main]]
    identifier = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/adriamercader/"
    weight = 35

[[menu.main]]
    identifier = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/amercader"
    weight = 40

[[menu.main]]
    identifier = "iNaturalist"
    pre = "<img src='/img/inat.png' width='21' height='21' />"
    url = "https://www.inaturalist.org/people/amercader"
    weight = 42

[[menu.main]]
    identifier = "Instagram"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/amercadero/"
    weight = 45

[[menu.main]]
    identifier = "RSS"
    pre = "<i class='fa fa-rss fa-lg'></i>"
    url = "/blog/index.xml"
    weight = 50


[markup.goldmark.renderer]
unsafe= true
